---
- name: Check uptime of all servers
  hosts: all
  gather_facts: false

  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: uptime_output

    - name: Show uptime result
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} uptime: {{ uptime_output.stdout }}"
